### ISSUE TITLE
Vue highlighting config

### ISSUE THREAD

**Issue by zetashift** [hadronized/kak-tree-sitter#285]
I'm unable to get Vue highlighting working:

```toml
[language.vue.grammar.source.git]
url = "https://github.com/ikatyang/tree-sitter-vue"
pin = "91fe2754796cd8fba5f229505a23fa08f3546c06"

[language.vue.grammar]
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.cc", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "vue.so"]
link_flags = ["-O3"]

[language.vue.queries.source.git]
url = "https://github.com/helix-editor/helix"
pin = "be307a420480178c1bc443992c8336f6471b8b7b"

[language.vue.queries]
path = "runtime/queries/vue"
```

Getting the following error in a `.vue` file: 
![image](https://github.com/hadronized/kak-tree-sitter/assets/1857826/f5aa3953-1a4e-417d-bda6-ba08717cb973)

### Info:

```
❯ kak-tree-sitter --version
kak-tree-sitter 0.5.4-dev-8d937bd

❯ ktsctl --version
ktsctl 0.3.3-dev-8d937bd
```

**Comment by zetashift** [comment]
Mhmhm, actually I'm getting this for Elixir as well:

```toml
[language.elixir.grammar.source.git]
url = "https://github.com/elixir-lang/tree-sitter-elixir"
pin = "511ea5e0088779e4bdd76e12963ab9a5fe99983a"

[language.elixir.grammar]
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.c", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "elixir.so"]
link_flags = ["-O3"]

[language.elixir.queries.source.git]
url = "https://github.com/helix-editor/helix"
pin = "be307a420480178c1bc443992c8336f6471b8b7b"

[language.elixir.queries]
path = "runtime/queries/elixir"
```
